name: Pincer
options:
  minimumXcodeGenVersion: 2.44.1
packages:
  Connect:
    url: https://github.com/connectrpc/connect-swift.git
    from: 1.2.0
  Textual:
    url: https://github.com/gonzalezreal/textual.git
    from: 0.3.1
settings:
  base:
    SWIFT_VERSION: 5.10
targets:
  Pincer:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: .
        includes:
          - "*.swift"
      - path: Generated
        includes:
          - "**/*.swift"
      - path: Assets.xcassets
        buildPhase: resources
    dependencies:
      - package: Connect
        product: Connect
      - package: Textual
        product: Textual
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.lox.pincer
        PRODUCT_NAME: Pincer
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        INFOPLIST_KEY_CFBundleDisplayName: Pincer
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
  PincerTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: ../PincerTests
        includes:
          - "**/*.swift"
    dependencies:
      - target: Pincer
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        GENERATE_INFOPLIST_FILE: YES
  PincerUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: ../PincerUITests
        includes:
          - "**/*.swift"
    dependencies:
      - target: Pincer
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        GENERATE_INFOPLIST_FILE: YES
