name: Pincer
options:
  minimumXcodeGenVersion: 2.44.1
settings:
  base:
    SWIFT_VERSION: 5.10
targets:
  Pincer:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: .
        includes:
          - "*.swift"
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.lox.pincer
        PRODUCT_NAME: Pincer
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        INFOPLIST_KEY_CFBundleDisplayName: Pincer
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
